version: '3.8'
services:
  authdb:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB1_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/authdb_init.sql:/docker-entrypoint-initdb.d/authdb_init.sql
      - authdbdata:/var/lib/postgresql/data

  vacationdb:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB2_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/db/vacationdb_init.sql:/docker-entrypoint-initdb.d/vacationdb_init.sql
      - vacationdbdata:/var/lib/postgresql/data

  auditdb:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB3_NAME}
    ports:
      - "5434:5432"
    volumes:
      - ./src/main/resources/db/auditdb_init.sql:/docker-entrypoint-initdb.d/auditdb_init.sql
      - auditdbdata:/var/lib/postgresql/data

volumes:
  authdbdata:
  vacationdbdata:
  auditdbdata:
