name: FrontendCheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: vacationplannerpro/vacation-planner-pro/src/main/frontend
      - run: cd vacationplannerpro/vacation-planner-pro/src/main/frontend
      - run: npm ci
      - run: npm run lint
