name: FrontendCheck

on:
  # runs on pushes to the main branch
  push:
    branches: [main]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [main]

jobs:
  build:
    # uses a Ubuntu Docker image (like a virtual machine)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"
          cache: "npm"

      - run: cd vacationplannerpro/vacation-planner-pro/src/main/frontend
      - run: npm ci
      - run: npm run lint
