name: FrontendCheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: cd vacationplannerpro/vacation-planner-pro/src/main/frontend
      - run: npm ci
      - run: npm run lint
